"""Property-based tests for `agent.tools.dispatch` (M8'/D).

The dispatcher is the determinism boundary: every IVR LLM tool call passes
through it, and validation failures must round-trip back to the LLM as
tool-error messages rather than crashing the call. The combinatorial space
(digits x menu options, benefit fields x value types, modes x reasons) is
exactly the sort of place example-based tests miss edge cases.

Hypothesis explores the validation matrix via `@given` strategies; each
property below corresponds to a specific dispatcher invariant from `tools.py`.
The async dispatcher is driven via `asyncio.run` inside sync tests so that
Hypothesis's example-shrinking machinery composes cleanly with pytest-asyncio
(the @given decorator wraps the test in a sync function, which would otherwise
collide with auto-mode async detection).
"""

from __future__ import annotations

import asyncio
from typing import get_args

from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from agent import tools
from agent.schemas import (
    BenefitField,
    CallMode,
    CompleteCallReason,
    HangupIntent,
    ToolCall,
)

from .conftest import MakeSession

# DTMF wire alphabet — same as `SendDTMFArgs.digits` pattern. Strategies
# generate strings within the schema's bounds so we exercise dispatcher
# (contextual) validation rather than Pydantic (structural) rejection.
_DTMF_ALPHABET = "0123456789*#"
_UNIVERSAL_DTMF_KEYS = frozenset("#*")
_BENEFIT_FIELDS: tuple[BenefitField, ...] = get_args(BenefitField)
_COMPLETE_CALL_REASONS: tuple[CompleteCallReason, ...] = get_args(CompleteCallReason)

# `make_session` is a factory fixture: each test invokes `make_session()`
# itself to mint a fresh `CallSession` per Hypothesis example, so the default
# function-scoped warning doesn't apply. `max_examples=50` keeps the suite
# fast (~1s for the whole file) while still covering the validation matrix.
_HYPOTHESIS_SETTINGS = settings(
    max_examples=50,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)


# Strategies -----------------------------------------------------------------

# Bounded by `SendDTMFArgs` schema (1-20, DTMF alphabet). Anything outside
# these bounds gets rejected by Pydantic before the contextual check fires,
# which is already covered by example-based tests.
_dtmf_digits = st.text(alphabet=_DTMF_ALPHABET, min_size=1, max_size=20)
# Menu options the dispatcher checks against. Keep the list bounded — real
# IVR menus rarely exceed 9 options. Empty list is a meaningful case (no
# menu seen → any digits accepted) and is generated by `min_size=0`.
_menu_options = st.lists(
    st.sampled_from("0123456789"),
    min_size=0,
    max_size=10,
    unique=True,
)
_benefit_field = st.sampled_from(_BENEFIT_FIELDS)
# Free-form reason text for `fail_with_reason`. Bounded by the schema's 1-120
# range; text() is unbounded by default which would tar-pit shrinking on
# pathological strings.
_reason_text = st.text(min_size=1, max_size=120)
_CALL_MODES: tuple[CallMode, ...] = get_args(CallMode)
_call_mode = st.sampled_from(_CALL_MODES)


# Properties -----------------------------------------------------------------


@given(digits=_dtmf_digits, menu_options=_menu_options)
@_HYPOTHESIS_SETTINGS
def test_send_dtmf_allowlist_property(
    make_session: MakeSession,
    digits: str,
    menu_options: list[str],
) -> None:
    """`send_dtmf` accepts iff every digit is universal (#, *) or appears in
    `recent_menu_options` — or `recent_menu_options` is empty (no menu seen).

    The dispatcher iterates digit-by-digit and rejects on the first mismatch;
    this property locks in that behavior across the full digit/menu matrix.
    """
    session = make_session(recent_menu_options=list(menu_options))
    result = asyncio.run(
        tools.dispatch(ToolCall(name="send_dtmf", args={"digits": digits}), session)
    )

    if not menu_options:
        # No menu seen yet → any digits go through.
        expected_accept = True
    else:
        allowed = _UNIVERSAL_DTMF_KEYS | set(menu_options)
        expected_accept = all(d in allowed for d in digits)

    assert result.success is expected_accept
    assert result.advanced_call_state is expected_accept
    if expected_accept:
        assert result.side_effect is not None
    else:
        assert result.side_effect is None


@given(field=_benefit_field, value=st.booleans())
@_HYPOTHESIS_SETTINGS
def test_record_benefit_bool_value_matrix_property(
    make_session: MakeSession,
    field: BenefitField,
    value: bool,
) -> None:
    """A `bool` value is accepted iff the field's expected type is `bool`.

    Pydantic v2 smart-mode would coerce `False` ↔ `0.0` silently — the
    dispatcher's explicit `isinstance(value, bool)` check is what prevents
    that. This property locks the distinction in.
    """
    session = make_session()
    result = asyncio.run(
        tools.dispatch(
            ToolCall(name="record_benefit", args={"field": field, "value": value}),
            session,
        )
    )

    expected_accept = field in {"active", "out_of_network_coverage"}
    assert result.success is expected_accept
    if expected_accept:
        assert result.advanced_call_state
        assert getattr(session.benefits, field) == value
    else:
        assert "expected float" in result.message
        assert "got bool" in result.message
        assert getattr(session.benefits, field) is None


@given(
    field=_benefit_field,
    # Keep finite + non-NaN so the only rejection comes from type/sign rules,
    # not Pydantic float-coercion edge cases.
    value=st.floats(min_value=-1e6, max_value=1e6, allow_nan=False, allow_infinity=False),
)
@_HYPOTHESIS_SETTINGS
def test_record_benefit_float_value_matrix_property(
    make_session: MakeSession,
    field: BenefitField,
    value: float,
) -> None:
    """A `float` value is accepted iff (1) the field's expected type is
    `float` AND (2) the value is non-negative. Bool fields reject any float."""
    session = make_session()
    result = asyncio.run(
        tools.dispatch(
            ToolCall(name="record_benefit", args={"field": field, "value": value}),
            session,
        )
    )

    is_float_field = field in {"deductible_remaining", "copay", "coinsurance"}
    expected_accept = is_float_field and value >= 0

    assert result.success is expected_accept
    if expected_accept:
        assert result.advanced_call_state
        assert getattr(session.benefits, field) == value
    elif not is_float_field:
        # Bool field got a float → type-mismatch rejection.
        assert "expected bool" in result.message
        assert "got float" in result.message
    else:
        # Float field got a negative value → sign-rejection.
        assert "non-negative" in result.message


@given(mode=_call_mode, reason=_reason_text)
@_HYPOTHESIS_SETTINGS
def test_fail_with_reason_uses_mode_specific_completion_reason(
    make_session: MakeSession,
    mode: CallMode,
    reason: str,
) -> None:
    """`fail_with_reason` sets `completion_reason` to `llm_aborted_{mode}`
    so dashboards can tell deliberate LLM aborts apart from watchdog timeouts.

    The free-form `reason` text lands on `completion_note` for logs/traces.
    """
    session = make_session(mode=mode)
    result = asyncio.run(
        tools.dispatch(ToolCall(name="fail_with_reason", args={"reason": reason}), session)
    )
    assert result.success
    assert result.advanced_call_state
    assert session.completion_reason == f"llm_aborted_{mode}"
    assert session.completion_note == reason
    assert session.done
    assert isinstance(result.side_effect, HangupIntent)


@given(reason=st.sampled_from(_COMPLETE_CALL_REASONS))
@_HYPOTHESIS_SETTINGS
def test_complete_call_accepts_every_literal_reason(
    make_session: MakeSession,
    reason: CompleteCallReason,
) -> None:
    """Each value in the `CompleteCallReason` literal is accepted and lands
    on `completion_reason` verbatim. Locks the literal ↔ dispatcher contract:
    if someone adds a literal variant without wiring dispatch, this fails."""
    session = make_session()
    result = asyncio.run(
        tools.dispatch(ToolCall(name="complete_call", args={"reason": reason}), session)
    )
    assert result.success
    assert session.completion_reason == reason
    assert session.done
    assert isinstance(result.side_effect, HangupIntent)


@given(
    # Anything outside the literal — bounded so shrinking is fast. Filtering
    # out the legal reasons keeps the property focused on the rejection path.
    reason=st.text(min_size=1, max_size=30).filter(lambda s: s not in _COMPLETE_CALL_REASONS),
)
@_HYPOTHESIS_SETTINGS
def test_complete_call_rejects_non_literal_reasons(
    make_session: MakeSession,
    reason: str,
) -> None:
    """Anything outside `CompleteCallReason` is rejected by Pydantic before
    the dispatcher mutates state — `completion_reason` stays `None`."""
    session = make_session()
    result = asyncio.run(
        tools.dispatch(ToolCall(name="complete_call", args={"reason": reason}), session)
    )
    assert not result.success
    assert not result.advanced_call_state
    assert session.completion_reason is None
    assert not session.done


@given(call_count=st.integers(min_value=1, max_value=5))
@_HYPOTHESIS_SETTINGS
def test_transfer_to_rep_idempotent(
    make_session: MakeSession,
    call_count: int,
) -> None:
    """Repeated `transfer_to_rep` calls keep `rep_mode_index` at the value
    captured on the FIRST flip. The dispatcher uses `is None` to gate the
    assignment, so subsequent calls must not overwrite it even though
    `len(history)` may have grown.
    """
    session = make_session()
    assert session.mode == "ivr"
    assert session.rep_mode_index is None

    # First call captures the index; subsequent calls must not overwrite it.
    first_result = asyncio.run(tools.dispatch(ToolCall(name="transfer_to_rep", args={}), session))
    assert first_result.success
    assert session.mode == "rep"
    first_index = session.rep_mode_index
    assert first_index is not None

    for _ in range(call_count - 1):
        result = asyncio.run(tools.dispatch(ToolCall(name="transfer_to_rep", args={}), session))
        assert result.success
        assert session.mode == "rep"
        # `rep_mode_index` is frozen at the first flip's value.
        assert session.rep_mode_index == first_index
